import os
import json
import re

from dotenv import load_dotenv
from groq import Groq


load_dotenv()

client = Groq(
    api_key=os.getenv("GROQ_API_KEY")
)


def _extract_json(text: str):
    """
    Extract a JSON object even if the model wraps it
    in markdown fences or surrounding text.
    """

    if not text:
        raise ValueError("Groq returned an empty response.")

    text = text.strip()

    # Remove markdown fences
    text = re.sub(
        r"^```(?:json)?\s*",
        "",
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r"\s*```$",
        "",
        text
    )

    text = text.strip()

    # Direct JSON
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Find first JSON object
    start = text.find("{")
    end = text.rfind("}")

    if start == -1 or end == -1 or end <= start:
        raise ValueError(
            f"Groq did not return a JSON object: {text}"
        )

    json_text = text[start:end + 1]

    try:
        return json.loads(json_text)

    except json.JSONDecodeError as error:
        raise ValueError(
            f"Groq returned invalid JSON: {error}\n"
            f"Response: {text}"
        )


def analyze_finances(data):

    projection = []

    for item in (data.projection or []):

        projection.append({
            "date": str(item.date),
            "balance": float(item.cashBalance),
            "change": float(item.change),
            "description": item.description
        })

    financial_data = {
        "currentCash": float(data.currentCash),
        "startingCash": float(data.startingCash),
        "totalIncome": float(data.totalIncome),
        "totalExpenses": float(data.totalExpenses),

        "projection": projection,

        "risk": (
            data.risk.model_dump(
                exclude_none=True
            )
            if data.risk
            else {}
        ),

        "recommendations": [
            recommendation.model_dump(
                exclude_none=True
            )
            for recommendation in (
                data.recommendations or []
            )
        ]
    }

    financial_json = json.dumps(
        financial_data,
        separators=(",", ":"),
        ensure_ascii=False
    )

    prompt = f"""
You are CashPilot AI.

Analyze this real business cash-flow data:

{financial_json}

Return ONE JSON object with exactly these fields:

summary
riskExplanation
businessPattern
priorityAction
outlook
goodScenario
badScenario

Every value must be a string.

Use ONLY the supplied financial data.

SUMMARY:
Summarize the current cash position.

RISK:
Explain the main cash-flow risk using actual
amounts and dates.

BUSINESS PATTERN:
Identify a real pattern visible in the data.

PRIORITY ACTION:
Give the most important practical action.

OUTLOOK:
Explain the near-term financial outlook.

GOOD SCENARIO:
Describe one favorable timing outcome using
one existing future cash flow. Include its
actual amount and date.

BAD SCENARIO:
Describe one unfavorable timing outcome using
one existing future cash flow. Include its
actual amount and date.

The scenarios MUST be generated by the AI.

Do not invent transactions, amounts, dates,
customers, payments, income, expenses or events.

If future cash flows exist, generate both
scenarios.

Keep every field very concise.
Each field should be one short sentence.
Use ₹ for currency.

Return JSON only.
"""

    response = client.chat.completions.create(

        model="openai/gpt-oss-120b",

        messages=[
            {
                "role": "system",
                "content": (
                    "You are CashPilot AI. "
                    "Analyze supplied financial data. "
                    "Generate grounded good and bad "
                    "cash-flow scenarios. "
                    "Return one JSON object with "
                    "exactly seven string fields."
                )
            },
            {
                "role": "user",
                "content": prompt
            }
        ],

        temperature=0,

        max_completion_tokens=1400
    )

    text = response.choices[0].message.content

    print("\n===== GROQ RAW RESPONSE =====")
    print(text)
    print("=============================\n")

    result = _extract_json(text)

    required_fields = [
        "summary",
        "riskExplanation",
        "businessPattern",
        "priorityAction",
        "outlook",
        "goodScenario",
        "badScenario"
    ]

    for field in required_fields:

        if field not in result:

            raise ValueError(
                f"AI response missing required field: {field}"
            )

        if not isinstance(result[field], str):

            result[field] = str(
                result[field]
            )

    return result